# Generated by Django 2.0 on 2017-12-14 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Origine de crédit (Nom)')),
                ('default_origin', models.CharField(max_length=30, null=True, verbose_name='Origine de crédit (Code)')),
                ('budget_type', models.IntegerField(choices=[(0, 'CNRS'), (1, 'UPS')], verbose_name='Tutelle')),
                ('default_nature', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nature')),
                ('tva_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Code TVA')),
                ('domain', models.CharField(blank=True, max_length=100, null=True, verbose_name='Domaine fonctionnel')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif?')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Team', verbose_name='Equipe')),
            ],
            options={
                'verbose_name': 'Budget',
                'verbose_name_plural': 'Budgets',
                'db_table': 'budget',
                'ordering': ('team', 'name'),
            },
        ),
        migrations.CreateModel(
            name='BudgetLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=100, verbose_name='Equipe')),
                ('order_id', models.IntegerField(blank=True, null=True, verbose_name='ID de commande')),
                ('orderitem_id', models.IntegerField(blank=True, null=True, verbose_name="ID d'item de commande")),
                ('budget_id', models.IntegerField(verbose_name='ID de budget')),
                ('budget', models.CharField(max_length=100, verbose_name='Budget')),
                ('number', models.CharField(blank=True, max_length=20, null=True, verbose_name='N° de commande')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name="Date de l'acte")),
                ('nature', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nature')),
                ('budget_type', models.IntegerField(choices=[(0, 'CNRS'), (1, 'UPS')], verbose_name='Tutelle')),
                ('origin', models.CharField(blank=True, max_length=30, null=True, verbose_name='Origine')),
                ('provider', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fournisseur')),
                ('offer', models.CharField(blank=True, max_length=100, null=True, verbose_name='Offre/Commentaire')),
                ('product', models.CharField(blank=True, max_length=500, null=True, verbose_name='Désignation')),
                ('reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Référence')),
                ('quantity', models.IntegerField(blank=True, default=1, null=True, verbose_name='Quantité')),
                ('product_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Montant unitaire')),
                ('credit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Crédit')),
                ('debit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Débit')),
                ('confidential', models.BooleanField(default=False, verbose_name='Ligne confidentielle')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active?')),
            ],
            options={
                'verbose_name': 'Ligne budgétaire',
                'verbose_name_plural': 'Lignes budgétaires',
                'db_table': 'budget_line',
                'ordering': ('team', 'budget', 'date', '-order_id'),
            },
        ),
    ]
