# Generated by Django 2.0 on 2017-12-14 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(blank=True, max_length=100, null=True, verbose_name="Fournisseur d'origine")),
                ('name', models.CharField(max_length=500, verbose_name='Désignation')),
                ('packaging', models.CharField(blank=True, max_length=100, null=True, verbose_name='Conditionnement')),
                ('reference', models.CharField(max_length=100, verbose_name='Référence')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix')),
                ('offer_nb', models.CharField(blank=True, max_length=100, null=True, verbose_name='N° Offre')),
                ('nomenclature', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nomenclature')),
                ('expiry', models.DateTimeField(blank=True, help_text='Format jj/mm/aaaa', null=True, verbose_name="Date d'expiration")),
                ('last_change', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'db_table': 'product',
                'ordering': ('provider', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ProductCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Code')),
                ('title', models.CharField(max_length=250, verbose_name='Libellé')),
            ],
            options={
                'verbose_name': 'Nomenclature',
                'db_table': 'product_code',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='ProductSubType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Sous-type')),
            ],
            options={
                'verbose_name': 'Sous-type de produit',
                'verbose_name_plural': 'Sous-types de produit',
                'db_table': 'product_subtype',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Type de produit',
                'verbose_name_plural': 'Types de produit',
                'db_table': 'product_type',
            },
        ),
        migrations.AddField(
            model_name='productsubtype',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductType', verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.ProductType', verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='product',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.Provider', verbose_name='Fournisseur'),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.ProductSubType', verbose_name='Sous-type'),
        ),
    ]
