# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 19:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('is_local', models.BooleanField(default=False, verbose_name='Magasin ?')),
                ('is_service', models.BooleanField(default=False, verbose_name='Type service ?')),
                ('direct_reception', models.BooleanField(default=False, verbose_name='Réception automatique ?')),
                ('reseller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='provider.Provider', verbose_name='Revendeur')),
                ('users_in_charge', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Responsables')),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'ordering': ('name',),
            },
        ),
    ]
