# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=100, verbose_name='Equipe')),
                ('provider', models.CharField(max_length=100, verbose_name='Fournisseur')),
                ('number', models.CharField(blank=True, max_length=100, null=True, verbose_name='N° cde')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant total')),
                ('budget', models.CharField(max_length=100, verbose_name='Budget')),
                ('date_delivered', models.DateTimeField(auto_now_add=True, verbose_name='Date de réception')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Commentaires')),
                ('items', models.ManyToManyField(to='order.OrderItem', verbose_name='Produits')),
            ],
            options={
                'verbose_name': 'Historique',
                'verbose_name_plural': 'Historique',
                'db_table': 'history',
                'ordering': ('-date_delivered',),
            },
        ),
    ]
