# Generated by Django 2.0 on 2018-03-06 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='date_delivered',
            field=models.DateTimeField(verbose_name='Date de réception'),
        ),
    ]
