# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 19:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('filename', models.CharField(max_length=500, verbose_name='Désignation')),
                ('attached_file', models.FileField(upload_to='attachments/%Y/%m/%d', verbose_name='Pièce jointe')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'db_table': 'attachment',
            },
        ),
    ]
