# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item_type',
            field=models.IntegerField(choices=[(0, 'Produit'), (1, 'Frais'), (2, 'Remises'), (3, 'Autre')], default=0, verbose_name="Type d'item"),
        ),
    ]
